// Code generated by "stringer -type=Theme"; DO NOT EDIT.

package systheme

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Light-1]
	_ = x[Dark-2]
}

const _Theme_name = "UnknownLightDark"

var _Theme_index = [...]uint8{0, 7, 12, 16}

func (i Theme) String() string {
	if i < 0 || i >= Theme(len(_Theme_index)-1) {
		return "Theme(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Theme_name[_Theme_index[i]:_Theme_index[i+1]]
}
